blaze_url = https://blazedemo.com/

weborder_url = https://demo.weborder.net/
username = guest1@microworks.com
password = Guest1!

exercise1_url = http://automationexercise.com

smartbear = http://secure.smartbearsoftware.com/samples/testcomplete11/WebOrders/login.aspx

